### ISSUE TITLE
Impossible to send message on portal page

### ISSUE THREAD

**Issue by vyx06** [florinp/phpbb-messenger#12]
Hi,

It is possible to send message on all page, except on portal.
I used Bord3 portal extension.

Other thing, is it possible to add a send button in place of "Shift + enter" key ?

Thanks

**Comment by florinp** [comment]
For the moment has some issues with other extensions.

Yes is possible to add a send button but you must to change the css file and js file to do this.

**Comment by Galixte** [comment]
Since your last commit i can’t send message from chat box because the commands SHIFT+ENTER doesn’t work.

**Comment by florinp** [comment]
Are some problems with the url in chat.js and i'm working to solve this problem. I hope to finish soon.

**Comment by vyx06** [comment]
Hi, 

The problem to send message on portal page seems to be fix.
For the problem to key "shift+enter", no problem on my version. But I changed the code to use only enter key. Because on phone is not pratice to used the key combination !

thanks

**Comment by florinp** [comment]
this bug was fixed
