### ISSUE TITLE
All connected member in list

### ISSUE THREAD

**Issue by vyx06** [florinp/phpbb-messenger#17]
Hi,

Is it possible to add an option to view all connected users of forum in place of system friend ?
And so not display the disconnected users in list.

thanks

**Comment by florinp** [comment]
Yes is possible to add an option to view all connected users

**Comment by Galixte** [comment]
Hi @florinp,

you closed but it’s planned ?

**Comment by florinp** [comment]
I closed this issue because i don't have any plan to add this option

**Comment by vyx06** [comment]
I change the code to displayed all connected members.
Works in by board.
I think it is interresting to add this option in futur.
 
public function getFriends()
	{
		$sql = "
            SELECT u.user_id, 
                   u.username, 
                   u.username_clean, 
                   u.user_type, 
                   u.user_colour, 
                   s.session_id, 
                   s.session_time
            FROM ". USERS_TABLE ." AS u
            LEFT JOIN ". SESSIONS_TABLE ." AS s ON s.session_user_id = u.user_id
            WHERE u.user_type <> 2
            GROUP BY u.username
        ";
	
		
		$result = $this->phpbb_db->sql_query($sql);

		$friends = array();
		while($row = $this->phpbb_db->sql_fetchrow($result))
		{
			if ($row['session_time'] >= (time() - (intval($this->config['load_online_time'] * 60))))
			{
				if ((int)$this->user->data['user_id'] != $row['user_id'])
				{
					$friends[] = array(
						'user_id' => $row['user_id'],
						'username' => $row['username_clean'],
						'user_colour' => $row['user_colour'],
						'user_status' => ($row['session_time'] >= (time() - (intval($this->config['load_online_time'] * 60)))) ? 1 : 0,
						'inbox' => $this->getInboxFromId($row['user_id'])
					);
				}
			}
		}
		$this->phpbb_db->sql_freeresult();

		return $friends;
	}
