### ISSUE TITLE
Message box superimpose

### ISSUE THREAD

**Issue by vyx06** [florinp/phpbb-messenger#21]
Hi,

Open a fisrt conversation with user X, then a second conversation with user Y. Close conversation user X. 
-> Fisrt bug, the conversation Y location don't move near the tchat list.
Then Reopen conversation with X user
-> Second bug, the box is superimpose with the box Y.

<a href="http://www.hostingpics.net/viewer.php?id=443385Sanstitre.png"><img src="http://img11.hostingpics.net/thumbs/mini_443385Sanstitre.png" alt="Heberger image" /></a>

Thanks ;)

**Comment by florinp** [comment]
I fixed this in the latest commit 6d1dad540b8cccfb9bc9e080d740446f5e1c6bd7.

**Comment by vyx06** [comment]
ok fix for me too in last version.
