### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Galixte** [florinp/phpbb-messenger#5]
Hi @florinp,

when i want to activate this extension, in ACP, after click on “Go” button, i have a white page. No error/no message.

Have you tested it on phpBB 3.1.4 ?

--------------------

Also, could you take a look about that: https://www.phpbb.com/community/viewtopic.php?p=14053571#p14053571 ?

**Comment by florinp** [comment]
Can you post the apache2/nginx errors log?

**Comment by Galixte** [comment]
Hi,

of course, access.log:
```
XX.XXX.XXX.XXX - - [11/Jun/2015:14:52:06 +0200] "POST /adm/index.php?i=acp_extensions&sid=xxx&mode=main&action=enable&ext_name=florinp%2Fmessenger&hash=xxx HTTP/1.1" 500 222
```
And error.log:
```
[Thu Jun 11 14:52:07 2015] [error] [client XX.XXX.XXX.XXX] PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /var/www/domain.tld/ext/florinp/messenger/libs/database.php:16\nStack trace:\n#0 /var/www/domain.tld/ext/florinp/messenger/libs/database.php(16): PDO->__construct('sqlite:./../sto...')\n#1 /var/www/domain.tld/ext/florinp/messenger/ext.php(14): florinp\\messenger\\libs\\database->__construct()\n#2 /var/www/domain.tld/phpbb/extension/manager.php(187): florinp\\messenger\\ext->enable_step(false)\n#3 /var/www/domain.tld/includes/acp/acp_extensions.php(179): phpbb\\extension\\manager->enable_step('florinp/messeng...')\n#4 /var/www/domain.tld/includes/functions_module.php(674): acp_extensions->main('extensions', 'main')\n#5 /var/www/domain.tld/adm/index.php(81): p_master->load_active()\n#6 {main}\n  thrown in /var/www/domain.tld/ext/florinp/messenger/libs/database.php on line 16, referer: http://www.domain.tld/adm/index.php?i=acp_extensions&sid=xxx&mode=main&action=enable_pre&ext_name=florinp%2Fmessenger
```

**Comment by florinp** [comment]
SQLite extension for PDO is missing

**Comment by Galixte** [comment]
What ? I don’t use SQLite.

**Comment by florinp** [comment]
The extension does

**Comment by Galixte** [comment]
To store what data ? Why it’s not store in the same database as the board ?

**Comment by florinp** [comment]
Stores all messages. I thought it was a good idea at the time and i have plans to change this when i have some spare time.

**Comment by Galixte** [comment]
OK update to PHP 5.6 and installation works fine. But after add some friends i can’t use the Chat Box.

**Comment by Galixte** [comment]
Next here: https://github.com/florinp/phpbb-messenger/issues/11

Please close all issues wich are already fixed in issues section.
